sudo: required

matrix:
  include:
    - env: PLATFORM=lua5.1
      services:
        - docker
    - env: PLATFORM=lua5.2
      services:
        - docker
    - env: PLATFORM=lua5.3
      services:
        - docker

before_install:
  - docker/build_container.sh "$PLATFORM"

script:
  - docker/run_tests_in_container.sh "$PLATFORM"
